name: wccm
description: A new Flutter project.


version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.0
  flutter_duration_picker: ^1.0.4
  shared_preferences: ^0.5.2
  audioplayers: ^0.13.0
  cupertino_icons: ^0.1.2
  toast: ^0.1.5
  wakelock: ^0.1.2+5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true


  assets:
  - assets/images/bowl.png
  - assets/sounds/LaurenceBowlEnd.mp3

